### PR TITLE
Check if ast present

### LINKED ISSUE #2649: Yul debugging does not work with latest compiler
It is not possible to debug transactions compiled from yul code with the latest nightly solidity compiler. Note that we recently also added source maps for yul code.

### PR DESCRIPTION
**Pull request by yann300**
fix #2649
need https://github.com/ethereum/remix/pull/1485

### CODE REVIEW

File: src/lib/offsetToLineColumnConverter.js [hunk 1]
```diff
@@ -19,11 +19,17 @@ export class OffsetToLineColumnConverter extends Plugin {
...
-        if (source.id === file) {
-          this.lineBreakPositionsByContent[file] = this.sourceMappingDecoder.getLinebreakPositions(sources[filename].content)
-          break
+      const sourcesArray = Object.keys(sources)
+      if (!asts && file === 0 && sourcesArray.length === 1) {
+        // if we don't have ast, we process the only one available content
+        this.lineBreakPositionsByContent[file] = this.sourceMappingDecoder.getLinebreakPositions(sources[sourcesArray[0]].content)
+      } else {
+        for (var filename in asts) {
+          var source = asts[filename]
```
Comment (LianaHus) [inline src/lib/offsetToLineColumnConverter.js:28]: could you use const instead?
